apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "msa-project-fe.fullname" . }}-env
  labels:
    {{- include "msa-project-fe.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
