apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "msa-project-fe.fullname" . }}
  labels:
    {{- include "msa-project-fe.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "msa-project-fe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "msa-project-fe.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "msa-project-fe.fullname" . }}-env
            {{- range .Values.secretEnvFrom }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          startupProbe:
            httpGet:
              path: {{ .Values.probes.startup.path | default "/" | quote }}
              port: {{ .Values.service.port }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold | default 30 }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds | default 1 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path | default "/" | quote }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds | default 2 }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold | default 6 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path | default "/" | quote }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds | default 2 }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold | default 3 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
