nameOverride: ""
fullnameOverride: ""
image:
  repository: kylesungproject/msa-project
  tag: "8c5aa02"
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 8080
config:
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
env:
  secretName: "msa-project-be-secret"
  configMapName: "msa-project-be-config"
probes:
  startup:
    path: "/actuator/health"
    failureThreshold: 30
    periodSeconds: 5
    timeoutSeconds: 2
  liveness:
    path: "/actuator/health/liveness"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2
  readiness:
    path: "/actuator/health/readiness"
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    timeoutSeconds: 2
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
  - host: 127.0.0.1.nip.io
    paths:
    - path: /
      pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
dev:
  inlineSecret:
    enabled: false
    data: {}
nodeSelector: {}
tolerations: []
affinity: {}
