apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env.configMapName }}
  labels:
    {{- include "msa-project-be.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
